baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "hugo-PaperMod"

[params]
title = "Hugo Profile"
description = "Text about my cool site"
defaultTheme = "light"

[[menu.main]]
name = "Blog posts"
weight = 1
url = "posts/"
